### ISSUE TITLE
Call to GetToken() fails due to missing method set_KeyType()

### ISSUE THREAD

**Issue by HenrikProOfficeClausen** [kombit/tokenservice_oioidws-net#3]
Calling GetToken() to get a token for SF1500 (Serviceplatformen), I'm being hit with a "Method not found" exception. Apparently, some library method is not found in my scenario. It puzzles me that this is even possible - has anyone else hit this issue?

Probably related - the missing method **set_KeyType()** seems to be on this class:
https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.security.tokens.issuedsecuritytokenparameters?view=dotnet-plat-ext-8.0

[12:56:34 ERR] GetToken() failed for Bruger endpoint on customer {"Id": 9, "CustomerId": 303, "Name": "Test af dobbelt", "EntityID": "76b78924-4ca8-4451-a0ab-4df016a51888", "Active": true, "Cvr": "41333014", "$type": "Customer"}.
System.MissingMethodException: Method not found: 'Void System.ServiceModel.Security.Tokens.IssuedSecurityTokenParameters.set_KeyType(System.IdentityModel.Tokens.SecurityKeyType)'.
   at Digst.OioIdws.OioWsTrustCore.StsTokenService.CreateWSTrustTokenParameters(CustomBinding stsBinding)
   at Digst.OioIdws.OioWsTrustCore.StsTokenService.CreateTokenProvider(StsAuthenticationCase stsAuthenticationCase, SecurityToken authenticationToken, CustomBinding stsBinding)
   at Digst.OioIdws.OioWsTrustCore.StsTokenService.GetToken(StsAuthenticationCase stsAuthenticationCase, SecurityToken authenticationToken)
   at Digst.OioIdws.OioWsTrustCore.StsTokenServiceBase.GetToken()

**Comment by Zyano** [comment]
This happens because Microsoft changed the availability of the 'KeyType' property's set method.
Effectively this means the package is vulnerable and you can't update to the latest version of the System.ServiceModel package in your project due to this. I don't recall which package it is that specifically that breaks the comparability.

**Comment by thuannguy** [comment]
There’s a PR to fix this issue, assuming the codebase can move to .NET 10: https://github.com/kombit/tokenservice_oioidws-net/pull/6
